apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mongodb-pv
  resources:
    requests:
      storage: 1Gi
